--Magnitude

--total number of customers by country
select * from gold.dim_customers;
select country,count(distinct customer_id) as total_customers from gold.dim_customers group by country order by total_customers desc;

--total number of customers by gender
select gender, count(customer_key) as total_customers from gold.dim_customers group by gender;

--total products by category
select category,count(product_key) as total_products from gold.dim_products group by category order by total_products desc;

--average cost in each category
select category,round(avg(cost),2) as average_cost from gold.dim_products group by category;

--total revenue generated for each category
select
p.category,
sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join 
gold.dim_products as p
on f.product_key=p.product_key
group by p.category
order by total_revenue desc;

--total revenue generated by each customer
select
c.customer_key as customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join 
gold.dim_customers as c
on f.customer_key=c.customer_key
group by c.customer_key,
	c.first_name,
	c.last_name
order by total_revenue desc;

--distribution of sold items across countries
select 
c.country,
sum(s.quantity) as total_sold_items
from gold.dim_customers as c
left join gold.fact_sales as s
on c.customer_key=s.customer_key
group by c.country
order by total_sold_items desc;
